[package]
name = "simon-acl"
version.workspace = true
edition.workspace = true
authors = ["Simon"]
license = "GPL-3.0"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
